// Interactive .moat.yml creation from detected dependencies

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createInterface } from 'node:readline';
import { detectDependencies, SERVICE_CONFIGS } from './detect.mjs';
import { log, err, BOLD, DIM, CYAN, GREEN, YELLOW, RESET } from './colors.mjs';

function prompt(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((res) => {
    rl.question(question, (answer) => { rl.close(); res(answer.trim()); });
  });
}

/**
 * Interactive init: detect deps, prompt user, generate .moat.yml.
 * Called by `moat init` or automatically on first run when no .moat.yml exists.
 */
export async function initConfig(workspace, { auto = false } = {}) {
  const configPath = join(workspace, '.moat.yml');

  if (existsSync(configPath)) {
    if (!auto) {
      log('.moat.yml already exists. Delete it first to re-initialize.');
    }
    return false;
  }

  const detected = detectDependencies(workspace);

  if (detected.length === 0) {
    if (!auto) {
      log('No services detected. Creating empty .moat.yml.');
      writeFileSync(configPath, '# .moat.yml — Per-project Moat configuration\n# See: moat.example.yml for all options\n\nservices: {}\n');
    }
    return false;
  }

  // In auto mode (called during main flow), ask if user wants to configure
  if (auto) {
    if (!process.stdin.isTTY) return false;

    console.log('');
    log(`Detected services: ${BOLD}${detected.join(', ')}${RESET}`);
    const answer = await prompt(`  ${CYAN}?${RESET} Create .moat.yml with these services? ${DIM}[Y/n]${RESET} `);
    if (/^n(o)?$/i.test(answer)) {
      // Write marker so we don't ask again
      writeFileSync(configPath, '# .moat.yml — auto-generated (no services requested)\nservices: {}\n');
      return false;
    }
  } else {
    console.log('');
    log(`Detected services: ${BOLD}${detected.join(', ')}${RESET}`);
    console.log('');
  }

  // Let user toggle individual services
  const selected = [];
  for (const service of detected) {
    const config = SERVICE_CONFIGS[service];
    if (!config) continue;

    if (!auto) {
      const answer = await prompt(`  ${CYAN}?${RESET} Include ${BOLD}${service}${RESET} (${DIM}${config.image}${RESET})? ${DIM}[Y/n]${RESET} `);
      if (/^n(o)?$/i.test(answer)) continue;
    }
    selected.push(service);
  }

  if (selected.length === 0) {
    writeFileSync(configPath, '# .moat.yml — auto-generated (no services requested)\nservices: {}\n');
    log('Created .moat.yml (no services).');
    return false;
  }

  // Generate .moat.yml
  const lines = [
    '# .moat.yml — Per-project Moat configuration',
    '# Generated by `moat init`',
    '',
    'services:',
  ];

  const envLines = [];

  for (const service of selected) {
    const config = SERVICE_CONFIGS[service];
    lines.push(`  ${service}:`);
    lines.push(`    image: ${config.image}`);
    if (Object.keys(config.env).length > 0) {
      lines.push('    env:');
      for (const [k, v] of Object.entries(config.env)) {
        lines.push(`      ${k}: ${v}`);
      }
    }
    for (const [k, v] of Object.entries(config.appEnv)) {
      envLines.push(`  ${k}: ${v}`);
    }
  }

  if (envLines.length > 0) {
    lines.push('');
    lines.push('env:');
    lines.push(...envLines);
  }

  lines.push('');

  writeFileSync(configPath, lines.join('\n'));
  log(`Created ${BOLD}.moat.yml${RESET} with: ${GREEN}${selected.join(', ')}${RESET}`);
  return true;
}
